eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

#management:
#  endpoint:
#    gateway:
#      enabled: true


server:
  port: 8080

#spring:
#  main:
#    web-application-type: servlet
#    allow-bean-definition-overriding: true
#    name: gateway-security
#  cloud:
#    gateway:
#      routes:
#        - id: discovery-server
#          uri: http://localhost:8761/
#          predicates:
#            - Path=/eureka/web
#        - id: app-user-service
#          uri: http://localhost:9001/
#          predicates:
#            - Path=/api/v1/users/**
#        - id: gateway-security
#          uri: http://localhost:8080/
#          predicates:
#            - Path=/api/v1/auth
debug: true